library(dplyr)
m <- read.csv(file = 'D:/household_power_consumption.csv', sep = ';', header = TRUE, check.names = TRUE)
m$Date= as.Date(m$Date, format= "%d/%m/%Y")
m$DateTime= as.POSIXct(paste(m$Date, m$Time, format= "%d/%m/%Y %H:%M:%S"))
png(filename= "plot2.png", width =480, height = 480, units = "px")
with(m, plot(DateTime, Global_active_power, type = "l", col = "black", xlab = "Day", ylab = "Global Active Power (Kiolowatt)"))
dev.off()