library(dplyr)
m <- read.csv(file = 'D:/household_power_consumption.csv', sep = ';', header = TRUE, check.names = TRUE)
m$Date= as.Date(m$Date, format= "%d/%m/%Y")
m$DateTime= as.POSIXct(paste(m$Date, m$Time, format= "%d/%m/%Y %H:%M:%S"))
png("plot3.png", width =480, height = 480, units = "px")
plot(m$DateTime, m$Sub_metering_1, type = "l", xlab = "Day", ylab = "Energy Sub-Metering")
lines(m$DateTime,m$Sub_metering_2,col="red")
lines(m$DateTime,m$Sub_metering_3,col="blue")
legend("topright", col=c("black", "red", "blue"), lty=1, lwd=2,legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
dev.off()
